import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from src.config import GMAIL_ADDRESS, GMAIL_APP_PASSWORD, RECIPIENT_EMAIL


def build_section(title: str, emoji: str, color: str, items: list[dict], is_video: bool = False) -> str:
    """Builds a single section of the email (videos, news, blogs or papers)."""
    if not items:
        return ""

    items_html = ""
    for item in items:
        extra = ""
        if is_video and item.get("view_count"):
            extra = f"{item['view_count']:,} views &nbsp;·&nbsp; "

        items_html += f"""
        <div style="margin-bottom:20px; padding:16px; background:#f9f9f9;
                    border-radius:8px; border-left:4px solid {color};">
            <a href="{item['url']}" style="font-size:15px; font-weight:bold;
               color:#1a1a1a; text-decoration:none;">
                {item['title']}
            </a>
            <p style="margin:6px 0 0; color:#555; font-size:12px;">
                {item.get('channel') or item.get('source', '')}
                &nbsp;·&nbsp; {extra}⭐ {item['score']}/10
            </p>
            <p style="margin:6px 0 0; color:#777; font-size:12px;">
                {item.get('description', '')}
            </p>
        </div>
        """

    return f"""
    <h2 style="font-size:17px; border-bottom:2px solid {color};
               padding-bottom:8px; margin-top:32px;">
        {emoji} {title}
    </h2>
    {items_html}
    """


def build_email_html(
    videos: list[dict],
    articles: list[dict],
    blogs: list[dict],
    papers: list[dict],
) -> str:
    """Builds the full HTML email digest."""

    date_str = datetime.now().strftime("%B %d, %Y")
    total = len(videos) + len(articles) + len(blogs) + len(papers)

    sections = ""
    sections += build_section("Top AI Videos",    "📺",
                              "#FF0000", videos,   is_video=True)
    sections += build_section("Top AI News",       "📰", "#0057ff", articles)
    sections += build_section("AI Lab Blog Posts", "🏢", "#6200ea", blogs)
    sections += build_section("Research Papers",   "📄", "#00897b", papers)

    html = f"""
    <html>
    <body style="font-family:Arial, sans-serif; max-width:680px;
                 margin:auto; padding:24px; color:#1a1a1a;">

        <!-- Header -->
        <div style="background:#0057ff; padding:24px; border-radius:10px; margin-bottom:32px;">
            <h1 style="color:white; margin:0; font-size:24px;">🤖 Your AI Digest</h1>
            <p style="color:#cce0ff; margin:8px 0 0; font-size:14px;">
                {date_str} &nbsp;·&nbsp; {total} curated items
            </p>
        </div>

        {sections}

        <!-- Footer -->
        <div style="margin-top:40px; padding-top:16px; border-top:1px solid #eee;
                    color:#999; font-size:12px;">
            <p>Automatically generated by your AI News Agent every 3 days.</p>
            <p>Powered by YouTube · NewsAPI · ArXiv · Groq · GitHub Actions</p>
        </div>

    </body>
    </html>
    """
    return html


def send_digest(
    videos: list[dict],
    articles: list[dict],
    blogs: list[dict] = None,
    papers: list[dict] = None,
) -> None:
    """Sends the full AI digest email via Gmail SMTP to one or more recipients."""

    blogs = blogs or []
    papers = papers or []

    if not any([videos, articles, blogs, papers]):
        print("[Email] Nothing to send — no items passed the filter.")
        return

    # Support multiple recipients separated by commas
    recipients = [email.strip() for email in RECIPIENT_EMAIL.split(",")]

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🤖 Your AI Digest — {datetime.now().strftime('%B %d, %Y')}"
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = ", ".join(recipients)

    html_content = build_email_html(videos, articles, blogs, papers)
    msg.attach(MIMEText(html_content, "html"))

    print(f"[Email] Connecting to Gmail...")
    print(
        f"[Email] Sending to {len(recipients)} recipient(s): {', '.join(recipients)}")

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_ADDRESS, recipients, msg.as_string())

    print(f"[Email] ✅ Digest sent successfully!")


# ─── Quick test ─────────────────────────────────────────────────────
if __name__ == "__main__":
    test_videos = [{
        "type": "video", "title": "GPT-6 just dropped",
        "channel": "Two Minute Papers", "description": "Full breakdown of GPT-6.",
        "url": "https://youtube.com/watch?v=test1", "view_count": 250000, "score": 9,
    }]
    test_articles = [{
        "type": "article", "title": "OpenAI releases new model",
        "source": "TechCrunch", "description": "OpenAI has released a new flagship model.",
        "url": "https://techcrunch.com/test", "score": 8,
    }]
    test_blogs = [{
        "type": "article", "title": "Claude 4.6 is now available",
        "source": "Anthropic", "description": "Anthropic announces Claude 4.6 with new capabilities.",
        "url": "https://anthropic.com/test", "score": 9,
    }]
    test_papers = [{
        "type": "article", "title": "Attention Is All You Need — Revisited",
        "source": "ArXiv — Vaswani et al.", "description": "A new take on the transformer architecture.",
        "url": "https://arxiv.org/test", "score": 8,
    }]

    send_digest(test_videos, test_articles, test_blogs, test_papers)
